---
- name: Check and print OS Version
  debug:
    var: ansible_os_family

- name: generate /etc/hosts file for all hosts from host.ini file
  template:
    src: "templates/hosts.j2"
    dest: "/etc/hosts"
    mode: 0644

- name: Restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: restarted

- name: apt-get update repository cache ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install additional packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python3-cryptography
    - setools
    - libsemanage-common
    - policycoreutils-python-utils
