---
- name: Check and print OS Version
  debug:
    var: ansible_os_family

- name: generate /etc/hosts file for all hosts from host.ini file
  template:
    src: "templates/hosts.j2"
    dest: "/etc/hosts"
    mode: 0644

- block:    #================= Block REDHAT =================
  - name: Install additional packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python3
      - python3-pip
      - python-crypto
      - python2-cryptography
      - setools-console
      - policycoreutils-python
  
    when: ansible_os_family == "RedHat"


- block:    #================= Block DEBIAN =================
  - name: Install additional packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python3-cryptography
      - setools
      - libsemanage-common
      - policycoreutils-python-utils
  
    when: ansible_os_family == "Debian"