---
# tasks file for iscsi_initiator
- name: Install open-iscsi
  apt:
    name: open-iscsi
    state: latest

- name: Start open-iscsi and enabel it on boot
  service:
    name: open-iscsi
    state: started
    enabled: yes
  
- name: copy InitiatorName in file /etc/iscsi/initiatorname.iscsi from iqn variable
  lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    regexp: '^InitiatorName='
    line: InitiatorName={{ iqn }}
  notify:
    - Restart open-iscsi

- name: Discovery iSCSI target
  shell: iscsiadm -m discovery -t st -p {{ tgt_ip }}
  register: iscsi_discovery
  ignore_errors: true

- name: Connection iSCSI target
  shell: iscsiadm -m node -l -T {{ tgt_iqn }} -p {{ tgt_ip }}
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Check if iSCSI target is connected
  shell: iscsiadm -m session
  register: iscsi_session
  
- name: Print iSCSI session
  debug:
    var: iscsi_session.stdout_lines

- name: Install iSCSI multipath-tools
  apt:
    name: multipath-tools
    state: latest

- name: generate multipath.conf from j2 template and copy to an initiator
  template:
    src: "templates/multipath.conf.j2"
    dest: "/etc/multipath.conf"
    mode: 0644
  notify:
    - Reload multipath

- name: adding WWID to the list the list of allowed names /etc/multipath/wwids
  shell: multipath -a {{ mpath_dev }}
  notify:
    - Restart multipathd

- name: get string WWID from file /etc/multipath/wwids
  shell: cat /etc/multipath/wwids | egrep -i '^/\w+/' | tr -d '//'
  register: wwid
    
- name: Print WWID
  debug:
    var: wwid.stdout_lines
