---
# tasks file for gfs2_config
- block:    #================= Block DEBIAN =================
  - name: Installation lvm2-cluster gfs2-utils
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - lvm2
        - gfs2-utils
        - dlm-controld

  when: ansible_os_family == "Debian"

- block:    #================= Block REDHAT =================
  - name: Installation lvm2-cluster gfs2-utils
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - lvm2
        - lvm2-cluster
        - gfs2-utils
        - dlm

  when: ansible_os_family == "RedHat"

- name: Creating DLM and CLVM resources
  command: "{{ item }}"
  with_items:
    - "pcs property set stonith-enabled=false"
    - "pcs property set no-quorum-policy=freeze"
    - "pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true" 
    - "pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true"
    - "pcs constraint order start dlm-clone then clvmd-clone"
  no_log: true


- name: Creating GFS2 filesystem
  command: "{{ item }}"
  with_items:
    - "pvcreate /dev/mapper/otusDSK"
    - "vgreate -Ay -cy cluster_vg /dev/mapper/otusDSK"
    - "lvcreate -L1000M -n cluster_lv cluster_vg"
    - "mkfs.gfs2 -j3 -lock_dlm -t {{ cluster_name }}:gfs2 /dev/cluster_vg/cluster_lv"

- name: Creating GFS2 resource
  command: "{{ item }}"
  with_items:
    - "pcs resource create clusterfs Filesystem device=\"/dev/cluster_vg/cluster_lv\" directory=\"/mnt/gfs2\" fstype=\"gfs2\" \"options=noatime\" op monitor interval=10s on-fail=ignore clone interleave=true"
    - "pcs constraint order start clvmd-clone then clusterfs-clone"
    - "pcs constraint colocation add clusterfs-clone with clvmd-clone"