---
# tasks file for iscsi_target"]
      - name: Install targetcli
        apt:
          name: targetcli-fb
          state: latest

      - name: Start targetcli and enabel it on boot
        service:
          name: rtslib-fb-targetctl
          state: started
          enabled: yes

      - name: Copy targetcli config file
        copy:
          src: "{{ source_folder }}/saveconfig.json"
          dest: "{{ cfg_folder }}"
          mode: 0644
        notify:
          - Apply targetcli saveconfig