# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..3).each do |i|
  # Box settings
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false 

  # iscsi initiator 3 servers 
  config.vm.define "iscsi-int-#{i}" do |iscsi_target|
    iscsi_target.vm.hostname = "iscsi-int-#{i}"
    iscsi_target.vm.network "private_network", ip: "192.168.99.12#{i}"

    iscsi_target.vm.provider "virtualbox" do |vb|
      vb.name = "iscsi-int-#{i}"
      vb.memory = "1024"
      vb.cpus = '1'

    iscsi_target.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y open-iscsi
      sudo systemctl enable iscsid
      sudo systemctl start iscsid
      sudo systemctl start multipathd
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5poJ4s6T4Hh5Y2ITEWT5xsg/JM5606Kw4REWCQqdb4eKCHAzX5ojixpWmyXfG4XsSQ4sX2MSVdoc599W8Rvgb8ftKEPI30UGpl9nH3p9EMtek5su5oGnqiY0HhcgtzsFafFASo19+/snS3vwuM3UrDOSZWAFDKJmRAIzp00NnpxWh9swGPDd4IWEvwvgjuiahZa5PpxCPyTYIi+dZoca+hkyj1+BEN3pYMPWASjxAI9fq6Slyaud34MWUVG2QpBt8eMDC2leIAx6CMgiZ6EMpkYWFUFJXTVCE/Ao8AZBLHtf6fA1FiX3kjryVMldJcwAeZo5v1g/7HdX4JFDfapLCOgh+6pP0UXnXtRwpkjCjsHZUEXRR1kR3iQ0ewAfQnqnAw4XlsrvKy1HaAAomlsn6DsjnOTROJWfGUJM0KhSLHMvBiwlt1bmRxPwp/gwZnrOeKPtYiNftqTyb4eAsDyG/44lHLsaQWIHLGh/ukQ8nk7WegN58WT0/eGAQF5o1dtU= sergeyn@m-sergeyn-G10L" >> /home/vagrant/.ssh/authorized_keys
    SHELL
    end
  end
end
  # iscsi target server configuration with two disks
  (1..1).each do |i|
    config.vm.define "iscsi-tgt" do |iscsi_target|
      config.vm.box = "ubuntu/focal64"
      config.vm.box_check_update = false 
      iscsi_target.vm.hostname = "iscsi"
      iscsi_target.vm.network "private_network", ip: "192.168.99.111"
      config.vm.disk :disk, disk_ext: "vdi", primary: false, size: "1GB", name: "extdisk"


      iscsi_target.vm.provider "virtualbox" do |vb|
        vb.name = "iscsi_target"
        vb.memory = "1024"
        vb.cpus = '1'
      iscsi_target.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y targetcli-fb
        sudo systemctl enable rtslib-fb-targetctl
        sudo apt install qla-tools -y
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5poJ4s6T4Hh5Y2ITEWT5xsg/JM5606Kw4REWCQqdb4eKCHAzX5ojixpWmyXfG4XsSQ4sX2MSVdoc599W8Rvgb8ftKEPI30UGpl9nH3p9EMtek5su5oGnqiY0HhcgtzsFafFASo19+/snS3vwuM3UrDOSZWAFDKJmRAIzp00NnpxWh9swGPDd4IWEvwvgjuiahZa5PpxCPyTYIi+dZoca+hkyj1+BEN3pYMPWASjxAI9fq6Slyaud34MWUVG2QpBt8eMDC2leIAx6CMgiZ6EMpkYWFUFJXTVCE/Ao8AZBLHtf6fA1FiX3kjryVMldJcwAeZo5v1g/7HdX4JFDfapLCOgh+6pP0UXnXtRwpkjCjsHZUEXRR1kR3iQ0ewAfQnqnAw4XlsrvKy1HaAAomlsn6DsjnOTROJWfGUJM0KhSLHMvBiwlt1bmRxPwp/gwZnrOeKPtYiNftqTyb4eAsDyG/44lHLsaQWIHLGh/ukQ8nk7WegN58WT0/eGAQF5o1dtU= sergeyn@m-sergeyn-G10L" >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end
end