---
- hosts: all
  name: Installation NGINX Web Server
  become: yes

  vars:
    source_folder: ./MyWebSite
    destin_folder: /var/www/html

  tasks:

    - name: Check and print OS Version
      debug:
        var: ansible_os_family

    - block:    #================= Block DEBIAN =================

      - name: Install NGINX Web Server for Debian Family
        apt:
          name: nginx
          state: latest

      - name: Start NGINX Web Server and Enabel it on boot for Debian Family
        service:
          name: nginx
          state: started
          enabled: yes

      when: ansible_os_family == "Debian"

    - name: Copy files to /var/www/html
      copy:
        src: "{{ source_folder }}/{{ item }}"
        dest: "{{ destin_folder }}"
        mode: 0644
      loop:
        - index.html
        - otus.png
      notify:
        - Restart NGINX Debian

  handlers:
    - name: Restart NGINX Debian
      service:
        name: nginx
        state: restarted
      when: ansible_os_family == "Debian"

