---
- hosts: all
  name: "iscsi target and initiator installation and configuration"
  become: yes


  tasks:

    - block:    #================= Block Initiator =================
 
      - name: installation lvm2-cluster gfs2-utils on initiators
        apt:
          name: "{{ item }}"
          state: latest
        loop:
          - lvm2-cluster
          - gfs2-utils

      when: inventory_hostname in groups["iscsi-initiator"]

  handlers:
    - name: restart pcsd
      systemd:
        name: pcsd.service
        state: restarted

      when: inventory_hostname in groups["iscsi-initiator"]
